//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaCrucero
{
    using System;


    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MensajesError
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensajesError()
        {
        }

        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PagoElectronico.MensajesError", typeof(MensajesError).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al intentar realizar el Alta. Por favor intente nuevamente..
        /// </summary>
        internal static string ErrMensajeAlta
        {
            get
            {
                return ResourceManager.GetString("ErrMensajeAlta", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al intentar eliminar el registro. Por favor intente nuevamente..
        /// </summary>
        internal static string ErrMensajeBaja
        {
            get
            {
                return ResourceManager.GetString("ErrMensajeBaja", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al intentar realizar la búsqueda. Por favor intente nuevamente..
        /// </summary>
        internal static string ErrMensajeBusqueda
        {
            get
            {
                return ResourceManager.GetString("ErrMensajeBusqueda", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al intentar guardar el Cliente. Por favor intente nuevamente..
        /// </summary>
        internal static string ErrMensajeGuardarCliente
        {
            get
            {
                return ResourceManager.GetString("ErrMensajeGuardarCliente", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al intentar modificar el registro. Por favor intente nuevamente..
        /// </summary>
        internal static string ErrMensajeModificación
        {
            get
            {
                return ResourceManager.GetString("ErrMensajeModificación", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al intentar limpiar los datos. Por favor intente nuevamente..
        /// </summary>
        internal static string ErrMensajesLimpiar
        {
            get
            {
                return ResourceManager.GetString("ErrMensajesLimpiar", resourceCulture);
            }
        }
    }
}
